# Generated by Django 3.2.8 on 2022-03-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrydata',
            options={'verbose_name_plural': 'Country Population Data'},
        ),
    ]
