# Generated by Django 3.2.8 on 2022-03-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard2', '0002_alter_countrydata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydata',
            name='population',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=30),
        ),
    ]
