# Generated by Django 3.2.8 on 2022-03-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='options',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question',
        ),
    ]
